---
- hosts: localhost
  connection: local
  tasks:
  - debug: var=manager_address 

- hosts: localhost
  connection: local
  become: yes
  roles:
  - { role: swarm, swarm_type_of_node: worker, swarm_manager_address: '{{manager_address}}'}  
