#!/usr/bin/env groovy

import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
 }   

pipeline {
	agent any

	stages {

		stage('Terraform: deployment') {

			steps {
                         sh 'echo efe7656e-5c56-bf4f-9bd9-8910d6511b71 >/home/jenkins/.vault-token'
                       ansiColor('xterm') {
                         dir("${WORKSPACE}/terraform"){
                           sh 'terraform init'
                           sh 'terraform apply --auto-approve'
                           sh "terraform state pull > ${WORKSPACE}/ansible1/terraform.tfstate"
                          } 
                         }          
		}
		}

		stage('Ansible: configure management node') {
			steps {
                      dir("${WORKSPACE}/ansible1"){
                      sh 'ls -l'
                      sh 'ansible1-playbook -i ./terraform_inventory.sh --private-key ../terraform/id_rsa install_ansible1.yml' 
                    }
                   }
		}

		stage('Ansible: configure swarm master') {
			steps {
                         dir ("${WORKSPACE}/terraform"){
                          script {
                           def user = "terraform output | grep user | sed 's/^.*= //'".execute().text
                           def host = "terraform output | grep node | sed 's/^.*= //'".execute().text
                           }
                         
                         sh 'ssh -i id_rsa ${user}@${host} ansible1-playbook -i ./terraform_inventory.sh main.yml'
                         } 
			}
		}
	}

}
