- name: Init "Swarm Mode" on the first manager.
  shell: docker swarm init
        --listen-addr {{ swarm_manager_address }}:{{ swarm_manager_port }}
        --advertise-addr {{ swarm_manager_address }}
  when: "docker_info.stdout.find('Swarm: active') == -1"

- name: Install python modules needed by helper service
  pip: 
    name: '{{item}}'
    state: latest
  with_items:
   - pip
   - bottle    

- name: Install swarm helper service
  block: 
  - name: Copy swarm-helper service unit
    copy:
     src: swarm-helper.service
     dest: /etc/systemd/system/
  - name: Copy swarm-helper script
    copy:
     src: swarm-helper.py
     dest: /root/
  - name: Enable swarm-helper service
    service: 
     name: swarm-helper
     state: started
     enabled: true   

